# Generated by Django 2.2 on 2020-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Message sending time')),
                ('username', models.CharField(max_length=100, verbose_name='TG user first name')),
                ('content', models.TextField(blank=True, verbose_name='Message content')),
                ('media', models.CharField(blank=True, max_length=100, verbose_name='path to mediafile bound to this message')),
                ('msg_type', models.PositiveIntegerField(default=0, verbose_name='message type (related to media type it was carrying')),
                ('reply_to', models.PositiveIntegerField(null=True, verbose_name='number of message which this one replies to')),
                ('fwd', models.BooleanField(default=False, verbose_name='is a forwarded message or not')),
                ('fwd_from', models.CharField(blank=True, max_length=255, verbose_name='forwarding source')),
                ('fwd_time', models.DateTimeField(blank=True, verbose_name='fwd source sending time')),
                ('inline', models.CharField(blank=True, max_length=255, verbose_name='inline message sender name')),
            ],
        ),
    ]
