# Generated by Django 2.2 on 2020-06-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fwd_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='forwarding source'),
        ),
        migrations.AlterField(
            model_name='message',
            name='fwd_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fwd source sending time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='inline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='inline message sender name'),
        ),
    ]
