# Generated by Django 2.2 on 2020-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200605_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fwd_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='forwarding source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='fwd_time',
            field=models.DateTimeField(null=True, verbose_name='fwd source sending time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='inline',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='inline message sender name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.PositiveIntegerField(default=0, verbose_name='number of message which this one replies to'),
        ),
    ]
