# Generated by Django 3.0.7 on 2022-12-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20221229_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='mainapp.MediaFile'),
        ),
    ]
